### ISSUE TITLE
Expiration date does not work

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/FormBuilder#119] opened 2015-03-23 15:28 UTC
The problem was initially seen in Yosemite Chrome. I do not know yet if it is in other browsers too. I will check the other browsers in a bit and get back to you.

I changed the expiration date on the Honors Graduation RSVP application. It did not expire. I could access the page and see the form.  I also tried it for the Honors Retreat application
![screen shot 2015-03-23 at 10 28 12 am](https://cloud.githubusercontent.com/assets/10925312/6783375/5f6a03f2-d147-11e4-8b5f-68b2ae3f2eda.png)
.

**Comment by srirampotluri** [comment] 2015-03-23 19:04
Expiration date works with YOSEMITE SAFARI !!

**Comment by CarlSteven** [comment] 2015-03-26 01:59
Closing because after working with Sriram, we noted it worked as intended. He was able to see an expired form when logged in as the creator of the form. This is expected behavior.

**Closed as completed by CarlSteven** 2015-03-26 01:59 UTC

**Comment by hejalsoni** [comment] 2015-03-26 02:01
Oh okay! That's why I could see it. I'm sorry about the mistake!

On Wednesday, March 25, 2015, CarlSteven notifications@github.com wrote:

> Closing because after working with Sriram, we noted it worked as intended.
> He was able to see an expired form when logged in as the creator of the
> form. This is expected behavior.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DataAnalyticsinStudentHands/FormBuilder/issues/119#issuecomment-86292203
> .

## 

Hejal Soni
Residential Advisor at Cougar Village 2
University of Houston
