### ISSUE TITLE
Box deletion

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/FormBuilder#34] opened 2015-02-09 16:33 UTC
When I try to delete one box, it deletes the boxes below it, but not the boxes above it.

**Comment by CarlSteven** [comment] 2015-02-09 16:36
I think this is a duplicate of #2

Does the problem go away when you refresh the page after entering the form builder/editor?

**Comment by hejalsoni** [comment] 2015-02-09 16:40
It works now!

**Comment by CarlSteven** [comment] 2015-02-09 23:16
Thanks! That definitely means it's caused by #2 please continue tracking the issue there.

**Closed as completed by CarlSteven** 2015-02-09 23:16 UTC
