### ISSUE TITLE
Login discrepancies

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/FormBuilder#44] opened 2015-02-11 14:25 UTC
Somehow there are two different accounts set up. If I log in using my username, I can access a different account then when I log in using my email address. Formbuilder accepts my password both times though.

**Comment by CarlSteven** [comment] 2015-02-11 15:50
You have two accounts, most likely from registering twice?

**Comment by hejalsoni** [comment] 2015-02-11 15:52
I did not believe I registered twice. Is there anyway to check?

**Comment by CarlSteven** [comment] 2015-02-11 15:53
I checked and you have two accounts: one under username and one under e-mail address.

This is most likely the cause.

**Comment by hejalsoni** [comment] 2015-02-11 15:56
Okay! Sorry about that! We would need to prevent other users from creating the same problem. Would a proper solution be to clarify whether we want a username or email address in the registration box? When I login, it asks me for my email address, but the registration box asks me for a username. It's confusing.

**Comment by CarlSteven** [comment] 2015-02-11 15:58
This is fixed as of #38, pending push to testing URL. You should see it live later today.

**Closed as completed** 2015-02-13 14:19 UTC
